### PR TITLE
feat: Update DotPlot defaults to use square root of data length for bins

### PR DESCRIPTION
**Pull request by Azendae-Popo**
# 🥇 Generic Pull Request 🥇
### Purpose & Objective

***

- [ ] This PR satisfies the PR checklist.

### CODE REVIEW

**Comment by Azendae-Popo** [comment]
I updated the x ticks to be the bin values. This sometimes displays decimals in the x ticks. Is it better to just leave the x-axis to do the automatic ticks? @cmbengue-ec-intl 
image

**Comment by Azendae-Popo** [comment]
> > I updated the x ticks to be the bin values. This sometimes displays decimals in the x ticks. Is it better to just leave the x-axis to do the automatic ticks? @cmbengue-ec-intl image
> 
> I would round it to a whole number.

Rounding to the whole number still looks a bit off centered and it's a bit more obvious:

image

**Comment by cmbengue-ec-intl** [comment]
> > > I updated the x ticks to be the bin values. This sometimes displays decimals in the x ticks. Is it better to just leave the x-axis to do the automatic ticks? @cmbengue-ec-intl image
> > 
> > 
> > I would round it to a whole number.
> 
> Rounding to the whole number still looks a bit off centered and it's a bit more obvious:
> 
> image

You will need to set the tick labels to the rounded values while keeping the ticks at the nonrounded values.

**Comment by Azendae-Popo** [comment]
image

**Pull request merged**
