### PR TITLE
Add Scatter Plot to Chartly

### PR DESCRIPTION
**Pull request by Azendae-Popo**
# 🥇 Generic Pull Request 🥇
### Purpose & Objective

***

- [x] This PR satisfies the PR checklist.

### CODE REVIEW

**Comment by Azendae-Popo** [comment]
Line plot with scatter example:
https://chartly.s3.amazonaws.com/static/img/line_plot_with_scatter.jpg

**Comment by Azendae-Popo** [comment]
Scatterplot example

[scatter plot demo](https://chartly.s3.amazonaws.com/static/img/scatter_eg.jpg)

**Review by javhaan — APPROVED** [review]
Great work on this 🌵

**Review by cmbengue-ec-intl — APPROVED** [review]
This looks good. Good extension. 💯

**Pull request merged**
