### PR TITLE
fea: Add Contour Plot Hatching

### PR DESCRIPTION
**Pull request by Azendae-Popo**
# 🥇 Generic Pull Request 🥇
### Purpose & Objective

***

- [x] This PR satisfies the PR checklist.

### CODE REVIEW

**Comment by Azendae-Popo** [comment]
image

**Comment by Azendae-Popo** [comment]
image

**Comment by Azendae-Popo** [comment]
image

**Comment by Azendae-Popo** [comment]
Updated demo: 

image

**Comment by Azendae-Popo** [comment]
Updated grid demo:

image

**Comment by Azendae-Popo** [comment]
Darkened edges demo:

image

**Comment by Azendae-Popo** [comment]
image

**Review by cmbengue-ec-intl — APPROVED** [review]
Great work on this. 💯

**Pull request merged**
